### PR TITLE
Added to Mike's notes

### PR DESCRIPTION
**Pull request by alancalder**

### CODE REVIEW

**Comment by lbaumo** [comment]
this conflict is so complicated, I don't know if we can ever resolve it

**Comment by lbaumo** [comment]
I think the only viable solution is to give up

**Comment by rherbonnet** [comment]
just throw it all away, too complicated

**Comment by lbaumo** [comment]
> just throw it all away, too complicated

I can't believe you would be so negative. This has brought the whole group down.

**Pull request merged**
